# https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    clusterName: macos-minikube
    tags: ["env:sandbox","owner:narbais","version:20230809"]
  features:
    apm:
      enabled: true
    usm:
      enabled: false
    logCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
    cws:
      enabled: true
    cspm:
      enabled: true
    admissionController:
      enabled: true