# https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secrets
        keyName: api-key
      appSecret:
        secretName: datadog-secrets
        keyName: app-key
    clusterName: macosarm-minikube
    tags: ["env:sandbox","owner:narbais","version:20240115","laptop:macosarm"]
    kubelet:
      tlsVerify: false # default: true
  features:
    eventCollection:
      collectKubernetesEvents: true
    kubeStateMetricsCore:
      enabled: true
    admissionController:
      enabled: true
    clusterChecks:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    apm:
      enabled: true