# Config doc: https://opentelemetry.io/docs/collector/configuration/

receivers:
  # Data sources: metrics
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      # swap:
  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      # grpc:
      http:
  # Data sources: metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["localhost:8888"]

processors:
  batch:

exporters:
  # Data sources: traces, metrics, logs
  logging:
    loglevel: debug
  # Data sources: traces, metrics
  otlphttp:
    endpoint: http://jaeger_app:4320/api
  # Data sources: traces
  jaeger:
    endpoint: "jaeger_app:14250"
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
      # exporters: [logging, otlphttp]
      # exporters: [otlphttp]
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [batch]
      exporters: [logging]